# Generated by Django 4.2 on 2023-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientesF", "0003_alter_veiculo_cliente_servico"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razao_social", models.CharField(max_length=255)),
                ("cnpj", models.CharField(max_length=18)),
                ("nome_fantasia", models.CharField(max_length=255)),
                ("segmento", models.CharField(max_length=100)),
                ("contato", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                ("cep", models.CharField(max_length=10)),
                ("celular", models.CharField(blank=True, max_length=20, null=True)),
                ("endereco", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("email", models.EmailField(max_length=255)),
                ("site", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
