# Generated by Django 4.2 on 2023-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesF', '0005_alter_cliente_cep_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='hora_cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='hora_cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='hora_cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='hora_cadastro',
            field=models.TimeField(auto_now=True),
        ),
    ]
