# Generated by Django 4.2 on 2023-04-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientesF', '0006_cliente_data_cadastro_cliente_hora_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='contato',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='estado',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fantasia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='razao_social',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='site',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
