import datetime

from django.db import models

class ClienteFisica(models.Model):
    Nome = models.CharField(max_length=100, null=False, blank=False)
    Data_Cadastro = models.DateField(auto_now=True)
    Hora_Cadastro = models.TimeField(auto_now=True)
    Nascimento = models.DateField(max_length=8, null=False, blank=False)
    Sobrenome = models.CharField(max_length=255, null=False, blank=False)
    CPF = models.CharField(max_length=14, null=False, blank=False)
    Profissao = models.CharField(max_length=255, null=False, blank=False)
    Telefone = models.CharField(max_length=14, null=False, blank=False)
    Celular = models.CharField(max_length=15, null=False, blank=False)
    Cep = models.CharField(max_length=9)
    Endereco = models.CharField(max_length=100)
    Cidade = models.CharField(max_length=100)
    Bairro = models.CharField(max_length=100)
    Estado = models.CharField(max_length=50)
    UF = models.CharField(max_length=2, null=False, blank=False)
    Email = models.EmailField(max_length=100, null=False, blank=False)
    Mensagem = models.CharField(max_length=100, null=False, blank=False)
    objetos = models.Manager()

class ClienteJuridica(models.Model):
    RazaoSocial = models.CharField(max_length=100, null=False, blank=False)
    Data_Cadastro = models.DateField(auto_now=True)
    Hora_Cadastro = models.TimeField(auto_now=True)
    CNPJ = models.CharField(max_length=18, null=False, blank=False)
    NomeFantasia = models.CharField(max_length=255, null=False, blank=False)
    Atividade = models.CharField(max_length=100, null=False, blank=False)
    Contato = models.CharField(max_length=255, null=False, blank=False)
    Telefone = models.CharField(max_length=14, null=False, blank=False)
    Celular = models.CharField(max_length=15, null=False, blank=False)
    Cep = models.CharField(max_length=9)
    Endereco = models.CharField(max_length=100)
    Cidade = models.CharField(max_length=100)
    Bairro = models.CharField(max_length=100)
    Estado = models.CharField(max_length=50)
    UF = models.CharField(max_length=2, null=False, blank=False)
    Email = models.EmailField(max_length=100, null=False, blank=False)
    Mensagem = models.CharField(max_length=100, null=False, blank=False)

class Fornecedor(models.Model):
    RazaoSocial = models.CharField(max_length=100, null=False, blank=False)
    Data_Cadastro = models.DateField(auto_now=True)
    Hora_Cadastro = models.TimeField(auto_now=True)
    CNPJ = models.CharField(max_length=13, null=False, blank=False)
    NomeFantasia = models.CharField(max_length=255, null=False, blank=False)
    Segmento = models.CharField(max_length=100, null=False, blank=False)
    Contato = models.CharField(max_length=200, null=False, blank=False)
    Telefone = models.CharField(max_length=11, null=False, blank=False)
    Celular = models.CharField(max_length=11, null=False, blank=False)
    Cep = models.CharField(max_length=9)
    Endereco = models.CharField(max_length=100)
    Cidade = models.CharField(max_length=100)
    Bairro = models.CharField(max_length=100)
    Estado = models.CharField(max_length=50)
    UF = models.CharField(max_length=2, null=False, blank=False)
    Email = models.EmailField(max_length=100, null=False, blank=False)
    Site = models.CharField(max_length=100, null=False, blank=False)
    Mensagem = models.CharField(max_length=100, null=False, blank=False)

class Veiculo(models.Model):
    RazaoSocial = models.CharField(max_length=200)
    Data_Cadastro = models.DateField(auto_now=True)
    Hora_Cadastro = models.TimeField(auto_now=True)
    Montadora = models.CharField(max_length=14)
    Modelo = models.CharField(max_length=200)
    Ano = models.DateField()
    Placa = models.CharField(max_length=8)
    Mensagem = models.CharField(max_length=100, null=False, blank=False)

