# Generated by Django 4.0.6 on 2023-04-18 22:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Nascimento', models.DateField(auto_now_add=True, verbose_name='Data:')),
                ('Sobrenome', models.CharField(max_length=255)),
                ('CPF', models.CharField(max_length=11)),
                ('Profissao', models.CharField(max_length=255)),
                ('Telefone', models.CharField(max_length=11)),
                ('Celular', models.CharField(max_length=11)),
                ('Cep', models.CharField(max_length=9)),
                ('Endereco', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('Email', models.EmailField(max_length=100)),
                ('Mensagem', models.CharField(max_length=100)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente_Juridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazaoSocial', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=13)),
                ('NomeFantasia', models.CharField(max_length=255)),
                ('Atividade', models.CharField(max_length=100)),
                ('Contato', models.CharField(max_length=255)),
                ('Telefone', models.CharField(max_length=11)),
                ('Celular', models.CharField(max_length=11)),
                ('Cep', models.CharField(max_length=9)),
                ('Endereco', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('Email', models.EmailField(max_length=100)),
                ('Mensagem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazaoSocial', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=13)),
                ('NomeFantasia', models.CharField(max_length=255)),
                ('Segmento', models.CharField(max_length=100)),
                ('Contato', models.CharField(max_length=200)),
                ('Telefone', models.CharField(max_length=11)),
                ('Celular', models.CharField(max_length=11)),
                ('Cep', models.CharField(max_length=9)),
                ('Endereco', models.CharField(max_length=100)),
                ('Cidade', models.CharField(max_length=100)),
                ('Bairro', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
                ('Email', models.EmailField(max_length=100)),
                ('Site', models.CharField(max_length=100)),
                ('Mensagem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazaoSocial', models.CharField(max_length=200)),
                ('Montadora', models.CharField(max_length=14)),
                ('Modelo', models.CharField(max_length=200)),
                ('Ano', models.DateField()),
                ('Placa', models.CharField(max_length=8)),
                ('Mensagem', models.CharField(max_length=100)),
            ],
        ),
    ]
