# Generated by Django 4.0.6 on 2023-04-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_fisica',
            name='Data_Cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cliente_fisica',
            name='Nascimento',
            field=models.DateField(max_length=8),
        ),
    ]
