# Generated by Django 4.0.6 on 2023-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_fisica_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente_juridica',
            name='Data_Cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='Data_Cadastro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Data_Cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
