# Generated by Django 4.0.6 on 2023-04-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_juridica_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente_Fisica',
            new_name='ClienteFisica',
        ),
        migrations.RenameModel(
            old_name='Cliente_Juridica',
            new_name='ClienteJuridica',
        ),
    ]
