# Generated by Django 4.0.6 on 2023-04-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_clientefisica_hora_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientejuridica',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
    ]
