# Generated by Django 4.0.6 on 2023-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_clientefisica_hora_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefisica',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientefisica',
            name='UF',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='clientejuridica',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clientejuridica',
            name='UF',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='UF',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='Hora_Cadastro',
            field=models.TimeField(auto_now=True),
        ),
    ]
